# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

product_data = [
                  ["Artichoke", nil],
  			          ["Galangal", nil],
                  ["Potato", "Red"],
                  ["Artichoke", "Jerusalem"],
                  ["Garlic", nil],
                  ["Potato", "Yukon Gold"],
                  ["Arugula", nil],
                  ["Ginger Root", nil],
                  ["Pumpkin", nil],
                  ["Asparagus", nil],
                  ["Gobo (Burdock Root)", nil],
                  ["Radicchio", nil],
                  ["Bok Choy", "Baby"],
                  ["Beans", "Green"],
                  ["Beans", "Fava"],
                  ["Radish", nil],
                  ["Beets", nil],
                  ["Green Lobak (Chinese Radish)", nil],
                  ["Radish", "Daikon"],
                  ["Beets", "Gold"],
                  ["Edamame", nil],
                  ["Renkon (Lotus Root)", nil],
                  ["Jicama", nil],
                  ["Rhubarb", nil],
                  ["Endive", "Belgian"],
                  ["Rutabaga", nil],
                  ["Parsnips", nil],
                  ["Kale", nil],
                  ["Peppers", "Green Bell"],
                  ["Peppers", "Yellow Bell"],
                  ["Peppers", "Orange Bell"],
                  ["Peppers", "Jalapeño"],
                  ["Peppers", "Habañero"],
                  ["Peppers", "Serrano"],
                  ["Peppers", "Pablano"],
                  ["Peppers", "Chili"],
                  ["Peppers", "Chipotle"],
                  ["Kale", "Lacinato"],
                  ["Melon", "Indian Bitter"],
                  ["Sin Qua (Chinese Okra)", nil],
                  ["Kale", "Red"],
                  ["Peas", "Snow"],
                  ["Salsify", "Black"],
                  ["Mushroom", "King Oyster"],
                  ["Spinach", nil],
                  ["Kohlrabi", nil],
                  ["Bok Choy", nil],
                  ["Broccoflower", nil],
                  ["Lettuce", nil],
                  ["Squash", "Acorn"],
                  ["Squash", "Banana"],
                  ["Squash", "Butternut"],
                  ["Squash", "Chayote"],
                  ["Squash", "Hubbard"],
                  ["Squash", "Opo"],
                  ["Squash", "Summer"],
                  ["Squash", "Sweet Dumpling"],
                  ["Leek", nil],
                  ["Broccoli", nil],
                  ["Broccoli", "Rabe"],
                  ["Lettuce", "Butter"],
                  ["Broccolini", nil],
                  ["Lettuce", "Frisee"],
                  ["Sprouts", "Brussel"],
                  ["Lettuce", "Iceberg"],
                  ["Lettuce", "Romaine"],
                  ["Cabbage", "Savoy"],
                  ["Cabbage", "Napa"],
                  ["Cabbage", "Green"],
                  ["Lobak", nil],
                  ["Carrot", nil],
                  ["Carrot", "Rainbow"],
                  ["Peas", "Sugar Snap"],
                  ["Cauliflower", nil],
                  ["Mushroom", "Beech"],
                  ["Mushroom", "Crimini"],
                  ["Mushroom", "Enoki"],
                  ["Mushroom", "Golden Enoki"],
                  ["Mushroom", "Maitake"],
                  ["Mushroom", "Portabello"],
                  ["Mushroom", "Shimeji"],
                  ["Mushroom", "Shitake"],
                  ["Mushroom", "Watercress"],
                  ["Mushroom", "Button"],
                  ["Mushroom", "Oyster"],
                  ["Mushroom", "Morel"],
                  ["Potato", "White"],
                  ["Potato", "Yellow"],
                  ["Potato", "Purple"],
                  ["Potato", "Sweet"],
                  ["Potato", "Okinawan Sweet"],
                  ["Potato", "Fingerling"],
                  ["Potato", "Russet"],
                  ["Potato", "Petite"],
                  ["Yam", nil],
                  ["Celery", nil],
                  ["Celeriac", nil],
                  ["Taro Leaf", nil],
                  ["Turnip", nil],
                  ["Chard", "Rainbow"],
                  ["Chard", "Swiss"],
                  ["Tomatillos", nil],
                  ["Tomatos", nil],
                  ["Tomatos", "Heirloom"],
                  ["Tomatos", "Cherry"],
                  ["Tomatos", "Plum"],
                  ["Tomatos", "Yellow"],
                  ["Tomatos", "Roma"],
                  ["Tomatos", "Beefsteak"],
                  ["Tomatos", "Green"],
                  ["Collard Greens", nil],
                  ["Mustard Greens", nil],
                  ["Dandelion Greens", nil],
                  ["Melon", "Winter"],
                  ["Melon", "Cantelope"],
                  ["Melon", "Honey Dew"],
                  ["Watermelon", nil],
                  ["Okra", nil],
                  ["Corn", "Sweet"],
                  ["Cucumber", "English"],
                  ["Cucumber", "Baby"],
                  ["Cucumber", nil],
                  ["Eggplant", nil],
                  ["Eggplant", "Fairytail"],
                  ["Onions", nil],
                  ["Onions", "Green"],
                  ["Onions", "Pearl"],
                  ["Onions", "Vidalia"],
                  ["Onions", "Sweet"],
                  ["Onions", "Yellow"],
                  ["Chives", nil],
                  ["Shallots", nil],
                  ["Zucchini", nil],
                  ["Cherries", nil],
                  ["Plums", nil],
                  ["Apricots", nil],
                  ["Peaches", nil],
                  ["Pluot", nil],
                  ["Pear", nil],
                  ["Nectarine", nil],
                  ["Apples", "Pick Lady"],
                  ["Apples", "Gala"],
                  ["Apples", "Granny Smith"],
                  ["Apples", "Honey Crisp"],
                  ["Apples", "Fuji"],
                  ["Apples", "Braeburn"],
                  ["Apples", "Golden Delicious"],
                  ["Apples", "Cripps Pink"],
                  ["Apples", "Red Delicious"],
                  ["Apples", "Envy"],
                  ["Apples", "Opal"],
                  ["Apples", "Jazz"],
                  ["Apples", "Macintosh"],
                  ["Raspberries", nil],
                  ["Blackberries", nil],
                  ["Blueberries", nil],
                  ["Blueberries", "Wild"],
                  ["Black Raspberries", nil],
                  ["Black Raspberries", "Wild"],
                  ["Strawberries", nil],
                  ["Gooseberries", nil],
                  ["Mulberries", nil],
                  ["Boysenberries", nil],
                  ["Elderberries", nil],
                  ["Huckleberries", nil],
                  ["Loganberries", nil],
                  ["Cranberries", nil],
                  ["Currents", "Red"],
                  ["Currents", "Black"],
                  ["Grapes", "Red"],
                  ["Grapes", "Green"],
                  ["Grapes", "Concord"],
                  ["Fennel", nil],
                  ["Ferns", "Fiddlehead"],

for product in product_data do
  Product.create(name: product[0], variety: product[1])
end
